### ISSUE TITLE
Update MHKiT Termonology 

### ISSUE THREAD

**Issue by kmruehl** [MHKiT-Software/MHKiT#19]
Based on https://github.com/MHKiT-Software/MHKiT-Python/pull/29 and team discussion, a few things need to be done to update the MHKiT Terminology:

- [ ] add column for Variable definition to [MHKiT terminology](https://mhkit-software.github.io/MHKiT/terminology.html)
- [x] add `D` for "Characteristic Length" to terminology
- [x] define `lambda_w` for "Wave Length" to terminology and update "Wave Number" definition
- [x] define "KC" as an acronym to terminology

**Comment by SeanPluemer** [comment]
@kmruehl What do you mean by "add a column for Variable definition to MHKiT terminology?"
Would you like me to change the "term" column to "variable?"

**Comment by kmruehl** [comment]
@SeanPluemer, this was a request from @ssolson to add a new column that maps each "term" to the "variable" used in MHKiT-Python and MHKiT-MATLAB.
