### ISSUE TITLE
README.md Updates

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT#21]
1) The description of how to work on the documentation makes sense, even the description of the featureBranch, but the instructions stop short of actually submitting a PR to MHKiT-Software/MHKiT. @ssolson I can take a stab at adding this description, unless you already assigned it to Sean. 

2) Should we have a list of unresolved issues with the Docs in the README? Would it not be better to simply just have Issues on each? @kmruehl

**Comment by ssolson** [comment]
Hey, Rebecca please take a stab at it. I would love another viewpoint on the laid out procedure!

**Comment by kmruehl** [comment]
@rpauly18 

1. I agree with the suggestion to include a PR step. Step 5 has issues that need to be updated. It says to push to a feature branch on ``origin``, and it should be pushed to your fork. There are also a few typos in Step 5
2. I agree that the unresolved issues with the Doc should be open as repository issues. I can create a few issues for them now. 
3. There's a formatting issue with Step 1. 'Once cloned used the" should be a fourth bullet.
