### ISSUE TITLE
Documentation doesn't compile with Sphinx Version: 3.2.0

### ISSUE THREAD

**Issue by kmruehl** [MHKiT-Software/MHKiT#31]
**Documentation doesn't compile with Sphinx Version: 3.2.0.** 

Use the following package versions to compile documentation:
- Documentation compiles with Sphinx Version: 3.1.1
-  Other packages requirements listed here:  https://github.com/MHKiT-Software/MHKiT/blob/master/README.md

**Comment by kmruehl** [comment]
This appears to be a compatibility issue  with **Sphinx Version: 3.2.0** and **sphinxcontrib-matlabdomain Version 0.11.2** . 

- When I remove all MATLAB API documentation this issue goes away
- When I revert to Sphinx Version: 3.1.1 this issue goes away.

**Comment by kmruehl** [comment]
@ssolson could this be your compile issue?

**Comment by akeeste** [comment]
Updated in #80
