### ISSUE TITLE
Package Dependencies

### ISSUE THREAD

**Issue by kmruehl** [MHKiT-Software/MHKiT#36]
@ssolson  Is this still the full list of python package dependencies? I thought we added some new ones, like `datetime`. If it's not the full list, can you provide a full list and I'll update the docs. 
https://mhkit-software.github.io/MHKiT/installation.html#requirements

@rpauly18 similar question, and I believe this is still a TBD issue for MHKiT-MATLAB, but do we have any MATLAB toolbox dependencies we should list?
https://mhkit-software.github.io/MHKiT/installation.html#id7

**Comment by ssolson** [comment]
Package dependencies are listed in [setup.py](https://github.com/MHKiT-Software/MHKiT-Python/blob/master/setup.py) under dependencies.
DEPENDENCIES = ['pandas>=1.0.0', 
                'numpy', 
                'scipy',
                'matplotlib', 
                'requests', 
                'pecos>=0.1.8',
                'fatpack',
                'lxml',
                'scikit-learn']

You can exclude lxml from the Docs list though because that is technically a pandas requirement.

**Comment by akeeste** [comment]
Updated in #80
