### ISSUE TITLE
MHKiT-MATLAB Install Instructions

### ISSUE THREAD

**Issue by Alex-McVey** [MHKiT-Software/MHKiT#47]
Need to note in the instructions for installing MHKiT in Matlab that if using an Anaconda environment, Matlab will not utilize any python interpreter outside of the base environment despite all indications that come from Matlab. This seems to be an issue on the Matlab side and it should be able to use different environments but for now I think it would help users to know that this issue exists.

**Comment by akeeste** [comment]
@simmsa Is this still an issue in recent MATLAB versions?

**Comment by simmsa** [comment]
@akeeste, this is difficult to definitively determine, due to lack of knowledge of how MATLAB implements Python support internally. Based on the latest MHKiT-MATLAB tests, which use Anaconda Python, this seems like this is no longer an issue and we can close this.
