### ISSUE TITLE
Need to update AP Value

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT#55]
This value needs to be updated due to the following issues:
https://github.com/MHKiT-Software/MHKiT-Python/issues/165
https://github.com/MHKiT-Software/MHKiT-Python/pull/236
https://github.com/MHKiT-Software/MHKiT-Python/issues/295

https://github.com/MHKiT-Software/MHKiT/blame/beaa580adee6389d93181ae4cd9886b7b5df429e/docs/source/installation.rst#L94

**Comment by akeeste** [comment]
This will be resolved by #60
