### ISSUE TITLE
Live documentation code blocks do not have syntax highlighting

### ISSUE THREAD

**Issue by simmsa** [MHKiT-Software/MHKiT#65]
The current live version of the documentation does not have syntax highlighted code blocks.

Live documentation:

![Screenshot 2024-05-16 at 9 22 26 AM](https://github.com/MHKiT-Software/MHKiT/assets/3704572/843a3856-063c-4c1b-9027-26de31aeb0c1)

On my local machine I built the documentation with:

```
nbsphinx==0.9.3
sphinxcontrib-matlabdomain==0.21.4
sphinxcontrib-bibtex==2.6.2
sphinx-rtd-theme==2.0.0
```

Which was installed with `pip install -U sphinxcontrib-bibtex sphinxcontrib-matlabdomain sphinx_rtd_theme nbsphinx` per the [README](https://github.com/MHKiT-Software/MHKiT?tab=readme-ov-file#step-2-downloadinstall-sphinx-package-and-extensions). Notably, these versions differ from the listed versions. Some package amongst these includes code block syntax highlighting.

![Screenshot 2024-05-16 at 9 22 53 AM](https://github.com/MHKiT-Software/MHKiT/assets/3704572/4d1a5c17-8e66-4719-8bf1-7ec0e6c9562f)

Long term this can be solved by a more consistent Build/CI step. In the short term does it make sense to use the latest versions of the above packages? The docs build properly (at least for me), and the addition of syntax highlighting contributes to an improved user experience.

**Comment by akeeste** [comment]
In #80, I updated the package version in the README to be the most recent. In these most recent version both python and matlab examples have proper syntax highlighting. This will be fixed in the next doc build after #80 is merged
